language: php

php:
  - 5.2
  - 5.3

before_install:
  - "git submodule update --init --recursive"

before_script:
  - "pear channel-discover pear.phing.info"
  - "pear install phing/phing"
  - "phpenv rehash"

script: "phing test"

notifications:
  irc: "irc.freenode.org#kohana"
  email: false
